name: Publish VuePress
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Blog Branche
      uses: actions/checkout@v2
      with:
        ref: source
    - name: Install Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set Git Config
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.VUE_NOTE_BLOG }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/vue_note
        chmod 600 ~/.ssh/vue_note
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'alex ceng'
        git config --global user.email 'izengjing.cn@gmail.com'
    - name: Install VuePress
      run: |
        npm install -g vuepress
        npm i
    - name: Build & Public VuePress
      run: |
        npm run docs:build
